---
deployment:
  tasks:
    - export DEPLOYPATH=/home/$USER/public_html/        
    - export DOMAINPATH="https://privacyrating.info"
    - export BASEPATH=""
    - yarn build
    - /bin/cp -R dist $DEPLOYPATH