// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'downloadButton': string;
  'example': string;
  'fadeInOut': string;
  'headerLabelDescription': string;
  'holder': string;
  'iframe': string;
  'iframeCodeBox': string;
  'overlayView': string;
  'privacyRatingSmall': string;
  'text': string;
}
export const cssExports: CssExports;
export default cssExports;
