// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'background': string;
  'button': string;
  'buttonBox': string;
  'codeBox': string;
  'colHeader': string;
  'downloadButton': string;
  'example': string;
  'fadeInOut': string;
  'holder': string;
  'hr': string;
  'nav': string;
  'overlayView': string;
  'pdfButton': string;
  'pdfViewer': string;
  'privacyRating': string;
  'privacyRatingSmall': string;
  'privacyRatingSmallButton': string;
  'text': string;
}
export const cssExports: CssExports;
export default cssExports;
