// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'holder': string;
  'iframe': string;
  'iframeCodeBox': string;
  'text': string;
}
export const cssExports: CssExports;
export default cssExports;
