// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Box': string;
  'holder': string;
  'image': string;
  'plainText': string;
  'subTitleBox': string;
}
export const cssExports: CssExports;
export default cssExports;
