// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'backgroundGray': string;
  'backgroundWhite': string;
  'button': string;
  'contactForm': string;
  'holder': string;
  'label': string;
  'pdfButton': string;
  'text': string;
}
export const cssExports: CssExports;
export default cssExports;
