// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'backgroundAbout': string;
  'backgroundCreate': string;
  'backgroundUse': string;
  'button': string;
  'holder': string;
  'image': string;
  'logos': string;
  'logosBox': string;
  'logosFrame': string;
  'plainTextAbout': string;
  'plainTextCreate': string;
  'plainTextUse': string;
  'subtitleAbout': string;
  'subtitleCreate': string;
}
export const cssExports: CssExports;
export default cssExports;
