// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'container': string;
  'footerText': string;
  'holder': string;
  'holderSmall': string;
  'labelSmall': string;
  'textLicense': string;
}
export const cssExports: CssExports;
export default cssExports;
