// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'circlebox': string;
  'cirleA': string;
  'cirleB': string;
  'cirleC': string;
  'cirleD': string;
  'cirleE': string;
  'cirleF': string;
  'cirleG': string;
  'holder': string;
  'privacyRatingFont': string;
}
export const cssExports: CssExports;
export default cssExports;
