// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'circleA': string;
  'circleB': string;
  'circleC': string;
  'circleD': string;
  'circleE': string;
  'circleF': string;
  'circleG': string;
  'element': string;
  'flexbox': string;
  'flexboxTitle': string;
  'holder': string;
  'holderSmall': string;
  'label': string;
  'privacyRatingFont': string;
}
export const cssExports: CssExports;
export default cssExports;
