// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'chip': string;
  'chipContainer': string;
  'colorA': string;
  'colorB': string;
  'colorC': string;
  'colorD': string;
  'colorE': string;
  'colorF': string;
  'colorG': string;
  'rank': string;
  'rankContainer': string;
  'result': string;
  'resultBox': string;
  'resultBoxHeader': string;
  'selected': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
