// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'colorA': string;
  'colorD': string;
  'colorG': string;
  'colorNone': string;
  'colouredDots': string;
  'holder': string;
  'label': string;
  'questionMark': string;
}
export const cssExports: CssExports;
export default cssExports;
