// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'domainName': string;
  'footer': string;
  'license': string;
  'questionMarker': string;
  'year': string;
}
export const cssExports: CssExports;
export default cssExports;
