// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'holder': string;
  'selected_category_0': string;
}
export const cssExports: CssExports;
export default cssExports;
