// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'colorA': string;
  'colorB': string;
  'colorC': string;
  'colorD': string;
  'colorE': string;
  'colorF': string;
  'colorG': string;
  'holder': string;
  'holderminimal': string;
}
export const cssExports: CssExports;
export default cssExports;
