// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'explain': string;
  'license': string;
  'licenseText': string;
  'tooltip': string;
}
export const cssExports: CssExports;
export default cssExports;
