// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'label': string;
  'labelFrame': string;
  'row': string;
  'spacer': string;
  'text': string;
}
export const cssExports: CssExports;
export default cssExports;
