// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'contactField': string;
  'form': string;
  'row': string;
  'subject': string;
  'text': string;
}
export const cssExports: CssExports;
export default cssExports;
