// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'answerButton': string;
  'headerIcon': string;
  'headerstyle': string;
  'justifyContentEnd': string;
  'noAnswer': string;
  'notSelected': string;
  'selected': string;
}
export const cssExports: CssExports;
export default cssExports;
