// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'answerButton': string;
  'answerContainer': string;
  'greenCheck': string;
  'headerIconBig': string;
  'headerIconSmall': string;
  'headerstyle': string;
  'headerstyleNotSelected': string;
  'justifyContentEnd': string;
  'notSelected': string;
  'question': string;
  'selected': string;
}
export const cssExports: CssExports;
export default cssExports;
