// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'answerButton': string;
  'answerContainer': string;
  'catStatus': string;
  'check': string;
  'cross': string;
  'headerIconBig': string;
  'headerstyle': string;
  'headerstyleNotSelected': string;
  'helpButton': string;
  'justifyContentEnd': string;
  'list-group-item': string;
  'notSelected': string;
  'popOver': string;
  'prefilled': string;
  'question': string;
  'questionText': string;
  'selected': string;
  'smallCircle': string;
  'urlInput': string;
}
export const cssExports: CssExports;
export default cssExports;
