// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'center': string;
  'fullscreen': string;
  'fullscreen-modal': string;
  'image-gallery': string;
  'image-gallery-bullet': string;
  'image-gallery-bullets': string;
  'image-gallery-bullets-container': string;
  'image-gallery-content': string;
  'image-gallery-description': string;
  'image-gallery-fullscreen-button': string;
  'image-gallery-icon': string;
  'image-gallery-image': string;
  'image-gallery-index': string;
  'image-gallery-left-nav': string;
  'image-gallery-play-button': string;
  'image-gallery-right-nav': string;
  'image-gallery-rtl': string;
  'image-gallery-slide': string;
  'image-gallery-slide-wrapper': string;
  'image-gallery-slides': string;
  'image-gallery-svg': string;
  'image-gallery-thumbnail': string;
  'image-gallery-thumbnail-image': string;
  'image-gallery-thumbnail-inner': string;
  'image-gallery-thumbnail-label': string;
  'image-gallery-thumbnails': string;
  'image-gallery-thumbnails-container': string;
  'image-gallery-thumbnails-wrapper': string;
  'image-gallery-using-mouse': string;
  'left': string;
  'right': string;
  'thumbnails-wrapper-rtl': string;
}
export const cssExports: CssExports;
export default cssExports;
