// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'arrow': string;
  'container': string;
  'icon': string;
  'label': string;
  'selected': string;
}
export const cssExports: CssExports;
export default cssExports;
