// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'arrow': string;
  'colorA': string;
  'colorB': string;
  'colorC': string;
  'colorD': string;
  'colorE': string;
  'colorF': string;
  'colorG': string;
  'container': string;
  'icon': string;
  'label': string;
  'notSelected': string;
  'selected': string;
}
export const cssExports: CssExports;
export default cssExports;
