// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'arrow': string;
  'colorA': string;
  'colorD': string;
  'colorG': string;
  'colouredDots': string;
  'holder': string;
  'label': string;
  'label__column': string;
  'recommendationText': string;
  'unfolded': string;
  'withHover': string;
}
export const cssExports: CssExports;
export default cssExports;
