// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'actionsRow': string;
  'backgroundCategories': string;
  'backgroundCategories1': string;
  'backgroundGray': string;
  'backgroundSlider': string;
  'button': string;
  'categories': string;
  'categoriesContainer': string;
  'colouredDots': string;
  'description': string;
  'downloadHandle': string;
  'holder': string;
  'hr': string;
  'icon': string;
  'label': string;
  'labelFrame': string;
  'pdfButton': string;
  'smallLabels': string;
  'spacer': string;
  'text': string;
}
export const cssExports: CssExports;
export default cssExports;
